# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  node: circleci/node@4.5.1
  jq: circleci/jq@2.2

jobs:
  test:
    docker:
      - image: cimg/node:14.17.6
    steps:
      - checkout
      - node/install-packages
      - run:
          name: test
          command: npm run test


workflows:
  build_test_package:
    jobs:
      - test
